### ISSUE TITLE
How do we compile this program?

### ISSUE THREAD

**Issue by everythingwillbetakenaway** [jpgsloan/Assimil8#1]
How do we compile this program?

**Comment by jonkri** [comment]
@everythingwillbetakenaway: Not sure if this helps, but I could build it by just double-clicking on Assimil8.xcodeproj to open the project in Xcode and then using the build options in the Product menu.

**Comment by jpgsloan** [comment]
thats correct! You just open the xcode project and build it from there. Also the code is a couple years old, and I'm not the original author of it (just convinced them to let me put it on github so that its not lost with time), so possibly needs some updates. If ever anyone wants to contribute changes to it, feel free to submit PR's, or fork the repo!
